server:
  port: 80
  error:
    path: /res/error
spring:
  mvc:
    static-path-pattern: /res/**

  session:
    timeout: 120m
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/algorithm?serverTimezone=UTC
    driver-class-name:  com.mysql.cj.jdbc.Driver


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
